modLoader="javafml"
loaderVersion="[47,)"
license="MIT License https://github.com/McJtyMods/RFToolsDimensions/blob/1.16/LICENCE"
issueTrackerURL="http://github.com/McJtyMods/RFToolsDimensions/issues"
displayURL="http://github.com/McJtyMods/RFToolsDimensions/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[mods]]
modId="rftoolsdim"
version="${file.jarVersion}"
displayName="RFToolsDimensions"
#updateJSONURL="http://myurl.me/" #optional
description='''
Create dimensions and power them with Forge Energy
'''
[[dependencies.rftoolsdim]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rftoolsdim]]
    modId="mcjtylib"
    mandatory=true
    versionRange="[1.20-8.0.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.rftoolsdim]]
    modId="rftoolsbase"
    mandatory=true
    versionRange="[1.20-5.0.0,)"
    ordering="AFTER"
    side="BOTH"
