modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://github.com/McJtyMods/RFToolsDimensions/issues"
displayURL="http://github.com/McJtyMods/RFToolsDimensions/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[mods]]
modId="rftoolsdim"
version="${file.jarVersion}"
displayName="RFToolsDimensions"
#updateJSONURL="http://myurl.me/" #optional
description='''
Create dimensions and power them with Forge Energy
'''
[[dependencies.rftoolsdim]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rftoolsdim]]
    modId="mcjtylib"
    mandatory=true
    versionRange="[1.15-4.1.7,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.rftoolsdim]]
    modId="rftoolsbase"
    mandatory=true
    versionRange="[1.15-1.1.6,)"
    ordering="AFTER"
    side="BOTH"